# Generated by Django 3.1.7 on 2021-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internaute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('numeroTelephone', models.CharField(max_length=75)),
                ('adresseMail', models.EmailField(max_length=254)),
                ('dateCreation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('dateEnvoi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
